version: "3.8"
services:
  db:
    container_name: employee-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: employee-database
    ports:
      - "5959:5432"
  pgadmin:
    container_name: pgadmin4-employee
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6969:80"
